apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-sentinel
  namespace: redis
spec:
  serviceName: redis-sentinel
  replicas: 3
  template:
    metadata:
      labels:
        redis-sentinel: "true"
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: init-sentinel
        image: busybox
        command: ['sh', '-c', 'until nslookup redis-master; do echo waiting for master; sleep 2; done;']
      containers:
      - name: redis-sentinel
        image: index-dev.qiniu.io/kelibrar/redis:4.0.6 
        imagePullPolicy: Always
        ports:
        - containerPort: 26379
          name: redis-sentinel
        env:
          - name: SENTINEL
            value: "true"
          - name: REDIS_APP_NAME
            value: "REDIS"
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: requirepass
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
      imagePullSecrets: 
        - name: registry-secret
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  labels:
    name: redis-sentinel
  namespace: redis
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    redis-sentinel: "true"
