#apiVersion: v1
#kind: Service
#metadata:
#  name: redis
#  labels:
#    app: redis
#spec:
#  ports:
#    - port: 6379
#  clusterIP: None
#  selector:
#    app: redis
#---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-slave
  labels:
    name: redis-slave
  namespace: redis
spec:
  serviceName: redis-slave
  replicas: 1 
  template:
    metadata:
      labels:
        name: redis-slave
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: init-slave
        image: busybox
        command: ['sh', '-c', 'until nslookup redis-sentinel; do echo waiting for sentinel; sleep 2; done;']
      containers:
      - name: redis-slave
        image: index-dev.qiniu.io/kelibrar/redis:4.0.6
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_APP_NAME
          value: "REDIS"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: requirepass
        volumeMounts:
        - name: redis-volume
          mountPath: /redis-master-data
        - name: redis-config
          mountPath: /etc/redis/
      imagePullSecrets: 
        - name: registry-secret
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
  volumeClaimTemplates:
  - metadata:
      name: redis-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ceph
      resources:
        requests:
          storage: 10Gi
