apiVersion: apps/v1beta1
kind: Deployment 
metadata:
  name: redis
  labels:
    name: redis
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: index-dev.qiniu.io/kelibrar/redis:3.2.8
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: requirepass
        volumeMounts:
        - name: redis-volume
          mountPath: /redis-master-data
      imagePullSecrets: 
        - name: registry-secret
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: redis-volume
