apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
  ports:
    - port: 6379
  selector:
    redis-master: "true"

---
apiVersion: apps/v1beta1
kind: Deployment 
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-master
        redis-master: "true"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: index-dev.qiniu.io/kelibrar/redis:3.2.8
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        env:
        - name: MASTER
          value: "true"
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: requirepass
        #resources:
        #  requests:
        #    memory: "256Mi"
        #    cpu: "250m"
        #  limits:
        #    memory: "512Mi"
        #    cpu: "500m"
        volumeMounts:
        - name: redis-master-volume
          mountPath: /redis-master-data
      imagePullSecrets:
        - name: registry-secret 
      volumes:
      - name: redis-master-volume
        persistentVolumeClaim:
          claimName: redis-master-volume
